import type { StageId } from "../domain/types";

export const guideCopy: Record<StageId, { role: string; module: string; title: string; why: string; inspect: string; chapter: number }> = {
  intro: { role: "Your mission", module: "Connected operation", title: "Get the promotion ready. Deliver the promise.", why: "Play the planning, warehouse, and transportation roles in one connected story.", inspect: "Every decision updates the same shared scenario.", chapter: 9 },
  demand: { role: "Demand planner", module: "Demand & replenishment", title: "Close the stock gap before the promotion.", why: "Compare forecast demand and the desired buffer with available stock. Approving the requirement gives sourcing a clear quantity to commit.", inspect: "Review forecast + target ending stock − available inventory.", chapter: 0 },
  sourcing: { role: "Supply coordinator", module: "Connected purchase order", title: "Turn the plan into a supplier commitment.", why: "The purchase order keeps the replenishment decision attached to the incoming stock. Confirmation prepares the receipt for the warehouse.", inspect: "Check the supplier, ordered quantity, and expected arrival.", chapter: 1 },
  inbound: { role: "Receiving operator", module: "Warehouse management", title: "Receive once. Update every downstream view.", why: "Posting the receipt adds the incoming stock to on hand. Order management sees that same inventory position immediately in this demo.", inspect: "Match the receipt to the purchase order and put-away location.", chapter: 3.8 },
  orders: { role: "Order coordinator", module: "Connected order execution", title: "Back the customer promise with inventory.", why: "Allocation reserves the ordered units. They remain physically in the warehouse, but are no longer available to another order.", inspect: "Compare on hand, reserved, and available before allocation.", chapter: 4.4 },
  fulfillment: { role: "Warehouse operator", module: "Warehouse management", title: "Take the order from shelf to sealed package.", why: "Start the pick task, then complete picking and packing. The package keeps its link to the same order all the way to dispatch.", inspect: "Find the pick location, required quantity, and package identifier.", chapter: 6.4 },
  shipment: { role: "Transport coordinator", module: "Transportation & visibility", title: "Carry the promise beyond the warehouse.", why: "Dispatch reduces on hand and releases the reservation. Advance each simulated carrier milestone to complete the shipment and order together.", inspect: "Check package readiness, carrier, and delivery milestones.", chapter: 7.7 },
  "control-tower": { role: "Operations lead", module: "Connected visibility", title: "See how every decision connects.", why: "The timeline, stock position, and linked records all read the same scenario. Trace the outcome back to the demand decision that started it.", inspect: "Review recorded events and the linked order and shipment.", chapter: 9 },
};
